import json
import os

def update_medicines():
    input_path = '/Users/yy/pro-test/zhongyi/assets/data/medicines.json'
    with open(input_path, 'r', encoding='utf-8') as f:
        medicines = json.load(f)
    
    real_medicines = [
        {"name": "辛夷", "pinyin": "Xin Yi", "latin_name": "Magnoliae Flos", "nature": "温", "flavor": ["辛"], "meridian": ["肺经", "胃经"], "effects": ["发散风寒", "通鼻窍"], "indications": ["风寒感冒", "鼻塞流涕"], "usage": "煎服，3-9g", "contraindications": [], "category": "解表药", "subcategory": "辛温解表药"},
        {"name": "细辛", "pinyin": "Xi Xin", "latin_name": "Asari Radix", "nature": "温", "flavor": ["辛", "温"], "meridian": ["肺经", "肾经", "心经"], "effects": ["解表散寒", "祛风止痛", "通窍"], "indications": ["风寒感冒", "头痛牙痛"], "usage": "煎服，1-3g", "contraindications": ["气虚多汗者慎用"], "category": "解表药", "subcategory": "辛温解表药"},
        {"name": "白芷", "pinyin": "Bai Zhi", "latin_name": "Angelicae Dahuricae Radix", "nature": "温", "flavor": ["辛"], "meridian": ["肺经", "胃经"], "effects": ["解表散寒", "祛风止痛", "通鼻窍"], "indications": ["风寒感冒", "头痛牙痛"], "usage": "煎服，3-9g", "contraindications": [], "category": "解表药", "subcategory": "辛温解表药"},
        {"name": "藁本", "pinyin": "Gao Ben", "latin_name": "Ligustici Rhizoma", "nature": "温", "flavor": ["辛"], "meridian": ["膀胱经"], "effects": ["祛风散寒", "除湿止痛"], "indications": ["风寒感冒", "巅顶头痛"], "usage": "煎服，3-9g", "contraindications": [], "category": "解表药", "subcategory": "辛温解表药"},
        {"name": "苍耳子", "pinyin": "Cang Er Zi", "latin_name": "Xanthii Fructus", "nature": "温", "flavor": ["辛", "苦"], "meridian": ["肺经"], "effects": ["发散风寒", "通鼻窍", "祛风湿"], "indications": ["风寒感冒", "鼻渊"], "usage": "煎服，3-9g", "contraindications": ["血虚头痛者不宜"], "category": "解表药", "subcategory": "辛温解表药"},
        {"name": "蔓荆子", "pinyin": "Man Jing Zi", "latin_name": "Viticis Fructus", "nature": "微寒", "flavor": ["辛", "苦"], "meridian": ["膀胱经", "肝经", "胃经"], "effects": ["疏散风热", "清利头目"], "indications": ["风热感冒", "头痛眩晕"], "usage": "煎服，6-12g", "contraindications": [], "category": "解表药", "subcategory": "辛凉解表药"},
        {"name": "淡豆豉", "pinyin": "Dan Dou Chi", "latin_name": "Sojae Semen", "nature": "凉", "flavor": ["辛", "甘", "微苦"], "meridian": ["肺经", "胃经"], "effects": ["解表", "除烦", "宣发郁热"], "indications": ["外感表证", "烦闷不眠"], "usage": "煎服，6-12g", "contraindications": [], "category": "解表药", "subcategory": "辛凉解表药"},
        {"name": "浮萍", "pinyin": "Fu Ping", "latin_name": "Spirodelae Herba", "nature": "寒", "flavor": ["辛"], "meridian": ["肺经", "膀胱经"], "effects": ["发汗解表", "透疹", "利水消肿"], "indications": ["风热感冒", "麻疹不透"], "usage": "煎服，3-9g", "contraindications": ["体虚多汗者慎用"], "category": "解表药", "subcategory": "辛凉解表药"},
        {"name": "龙胆草", "pinyin": "Long Dan Cao", "latin_name": "Gentianae Radix", "nature": "寒", "flavor": ["苦"], "meridian": ["肝经", "胆经"], "effects": ["清热燥湿", "泻肝胆火"], "indications": ["肝胆湿热", "目赤肿痛"], "usage": "煎服，3-6g", "contraindications": ["脾胃虚寒者慎用"], "category": "清热药", "subcategory": "清热燥湿药"},
        {"name": "苦参", "pinyin": "Ku Shen", "latin_name": "Sophorae Radix", "nature": "寒", "flavor": ["苦"], "meridian": ["心经", "肝经", "胃经"], "effects": ["清热燥湿", "杀虫", "利尿"], "indications": ["湿热泻痢", "湿疹瘙痒"], "usage": "煎服，4.5-9g", "contraindications": ["脾胃虚寒者慎用"], "category": "清热药", "subcategory": "清热燥湿药"},
        {"name": "秦皮", "pinyin": "Qin Pi", "latin_name": "Fraxinus Cortex", "nature": "寒", "flavor": ["苦", "涩"], "meridian": ["肝经", "胆经"], "effects": ["清热燥湿", "收涩止痢", "明目"], "indications": ["湿热泻痢", "目赤肿痛"], "usage": "煎服，6-12g", "contraindications": [], "category": "清热药", "subcategory": "清热燥湿药"},
        {"name": "白鲜皮", "pinyin": "Bai Xian Pi", "latin_name": "Dictamni Cortex", "nature": "寒", "flavor": ["苦", "寒"], "meridian": ["脾经", "胃经", "膀胱经"], "effects": ["清热燥湿", "祛风解毒"], "indications": ["湿热疮毒", "湿疹瘙痒"], "usage": "煎服，5-10g", "contraindications": ["脾胃虚寒者慎用"], "category": "清热药", "subcategory": "清热燥湿药"},
        {"name": "紫花地丁", "pinyin": "Zi Hua Di Ding", "latin_name": "Violae Herba", "nature": "寒", "flavor": ["苦", "辛"], "meridian": ["心经", "肝经"], "effects": ["清热解毒", "凉血消肿"], "indications": ["痈肿疮毒", "毒蛇咬伤"], "usage": "煎服，9-15g", "contraindications": [], "category": "清热药", "subcategory": "清热解毒药"},
        {"name": "野菊花", "pinyin": "Ye Ju Hua", "latin_name": "Chrysanthemi Flos", "nature": "微寒", "flavor": ["苦", "辛"], "meridian": ["肝经", "肺经"], "effects": ["清热解毒", "泻火平肝"], "indications": ["痈肿疮毒", "目赤肿痛"], "usage": "煎服，9-15g", "contraindications": [], "category": "清热药", "subcategory": "清热解毒药"},
        {"name": "大青叶", "pinyin": "Da Qing Ye", "latin_name": "Isatidis Folium", "nature": "寒", "flavor": ["苦"], "meridian": ["心经", "肺经"], "effects": ["清热解毒", "凉血消斑"], "indications": ["热入营血", "喉痹口疮"], "usage": "煎服，9-15g", "contraindications": ["脾胃虚寒者慎用"], "category": "清热药", "subcategory": "清热解毒药"},
        {"name": "青黛", "pinyin": "Qing Dai", "latin_name": "Indigo Naturalis", "nature": "寒", "flavor": ["咸"], "meridian": ["肝经"], "effects": ["清热解毒", "凉血消斑", "清肝泻火"], "indications": ["温毒发斑", "肺热咳嗽"], "usage": "1.5-3g，冲服", "contraindications": [], "category": "清热药", "subcategory": "清热解毒药"},
        {"name": "贯众", "pinyin": "Guan Zhong", "latin_name": "Cyrtomii Rhizoma", "nature": "微寒", "flavor": ["苦", "涩"], "meridian": ["肝经", "脾经"], "effects": ["清热解毒", "凉血止血", "杀虫"], "indications": ["风热感冒", "血热出血"], "usage": "煎服，5-10g", "contraindications": ["脾胃虚寒者慎用"], "category": "清热药", "subcategory": "清热解毒药"},
        {"name": "金荞麦", "pinyin": "Jin Qiao Mai", "latin_name": "Fagopyri Rhizoma", "nature": "凉", "flavor": ["苦"], "meridian": ["肺经"], "effects": ["清热解毒", "排脓祛瘀"], "indications": ["肺痈", "肺热咳嗽"], "usage": "煎服，15-45g", "contraindications": [], "category": "清热药", "subcategory": "清热解毒药"},
        {"name": "大血藤", "pinyin": "Da Xue Teng", "latin_name": "Sargentodoxae Caulis", "nature": "平", "flavor": ["苦"], "meridian": ["大肠经", "肝经"], "effects": ["清热解毒", "活血", "祛风止痛"], "indications": ["肠痈腹痛", "风湿痹痛"], "usage": "煎服，9-15g", "contraindications": ["孕妇慎用"], "category": "清热药", "subcategory": "清热解毒药"},
        {"name": "败酱草", "pinyin": "Bai Jiang Cao", "latin_name": "Patriniae Herba", "nature": "性微寒", "flavor": ["辛", "苦"], "meridian": ["胃经", "大肠经", "肝经"], "effects": ["清热解毒", "消痈排脓", "祛瘀止痛"], "indications": ["肠痈", "肺痈"], "usage": "煎服，6-15g", "contraindications": ["脾胃虚弱者慎用"], "category": "清热药", "subcategory": "清热解毒药"},
        {"name": "射干", "pinyin": "She Gan", "latin_name": "Belamcandae Rhizoma", "nature": "寒", "flavor": ["苦"], "meridian": ["肺经"], "effects": ["清热解毒", "利咽祛痰"], "indications": ["咽喉肿痛", "痰热咳喘"], "usage": "煎服，3-9g", "contraindications": ["脾虚便溏者慎用"], "category": "清热药", "subcategory": "清热解毒药"},
        {"name": "山豆根", "pinyin": "Shan Dou Gen", "latin_name": "Sophorae Radix", "nature": "寒", "flavor": ["苦"], "meridian": ["肺经", "胃经"], "effects": ["清热解毒", "利咽消肿"], "indications": ["咽喉肿痛"], "usage": "煎服，3-6g", "contraindications": ["脾胃虚寒者慎用"], "category": "清热药", "subcategory": "清热解毒药"},
        {"name": "马勃", "pinyin": "Ma Bo", "latin_name": "Lasiosphaerae Calvatiae", "nature": "平", "flavor": ["辛"], "meridian": ["肺经"], "effects": ["清热解毒", "利咽止血"], "indications": ["咽喉肿痛", "出血"], "usage": "煎服，1.5-6g", "contraindications": [], "category": "清热药", "subcategory": "清热解毒药"},
        {"name": "马齿苋", "pinyin": "Ma Chi Xian", "latin_name": "Portulacae Herba", "nature": "寒", "flavor": ["酸"], "meridian": ["肝经", "大肠经"], "effects": ["清热解毒", "凉血止血"], "indications": ["热毒血痢", "崩漏便血"], "usage": "煎服，9-15g", "contraindications": ["脾胃虚寒者慎用"], "category": "清热药", "subcategory": "清热解毒药"},
        {"name": "鸦胆子", "pinyin": "Ya Dan Zi", "latin_name": "Bruceae Fructus", "nature": "寒", "flavor": ["苦"], "meridian": ["大肠经", "肝经"], "effects": ["清热解毒", "止痢", "截疟"], "indications": ["热毒血痢", "疟疾"], "usage": "0.5-2g，装胶囊", "contraindications": ["脾胃虚寒者慎用"], "category": "清热药", "subcategory": "清热解毒药"},
        {"name": "赤芍", "pinyin": "Chi Shao", "latin_name": "Paeoniae Radix Rubra", "nature": "微寒", "flavor": ["苦"], "meridian": ["肝经"], "effects": ["清热凉血", "散瘀止痛"], "indications": ["热入血分", "瘀血肿痛"], "usage": "煎服，6-12g", "contraindications": ["血虚经闭者慎用"], "category": "清热药", "subcategory": "清热凉血药"},
        {"name": "紫草", "pinyin": "Zi Cao", "latin_name": "Arnebiae Radix", "nature": "寒", "flavor": ["甘", "咸"], "meridian": ["心经", "肝经"], "effects": ["清热凉血", "活血", "解毒透疹"], "indications": ["温病血热", "麻疹不透"], "usage": "煎服，5-10g", "contraindications": ["脾虚便溏者慎用"], "category": "清热药", "subcategory": "清热凉血药"},
        {"name": "白薇", "pinyin": "Bai Wei", "latin_name": "Cynanchi Radix", "nature": "寒", "flavor": ["苦", "咸"], "meridian": ["胃经", "肝经"], "effects": ["清热凉血", "利尿通淋", "解毒疗疮"], "indications": ["阴虚发热", "热淋"], "usage": "煎服，4.5-9g", "contraindications": [], "category": "清热药", "subcategory": "清虚热药"},
        {"name": "银柴胡", "pinyin": "Yin Chai Hu", "latin_name": "Stellariae Radix", "nature": "微寒", "flavor": ["甘"], "meridian": ["肝经", "胃经"], "effects": ["清虚热", "除疳热"], "indications": ["阴虚发热", "疳积发热"], "usage": "煎服，3-9g", "contraindications": [], "category": "清热药", "subcategory": "清虚热药"},
        {"name": "胡黄连", "pinyin": "Hu Huang Lian", "latin_name": "Picrorhizae Rhizoma", "nature": "寒", "flavor": ["苦"], "meridian": ["肝经", "胃经", "大肠经"], "effects": ["退虚热", "除疳热", "清湿热"], "indications": ["阴虚发热", "湿热泻痢"], "usage": "煎服，1.5-9g", "contraindications": ["脾胃虚寒者慎用"], "category": "清热药", "subcategory": "清虚热药"},
        {"name": "番泻叶", "pinyin": "Fan Xie Ye", "latin_name": "Sennae Folium", "nature": "寒", "flavor": ["甘", "苦"], "meridian": ["大肠经"], "effects": ["泻热行滞", "通便", "利水"], "indications": ["热结积滞", "水肿胀满"], "usage": "2-6g，泡服", "contraindications": ["孕妇慎用"], "category": "泻下药", "subcategory": "攻下药"},
        {"name": "芦荟", "pinyin": "Lu Hui", "latin_name": "Aloe", "nature": "寒", "flavor": ["苦"], "meridian": ["肝经", "大肠经"], "effects": ["泻下通便", "清肝泻火", "杀虫"], "indications": ["热结便秘", "惊痫抽搐"], "usage": "1-2g，入丸散", "contraindications": ["孕妇慎用"], "category": "泻下药", "subcategory": "攻下药"},
        {"name": "郁李仁", "pinyin": "Yu Li Ren", "latin_name": "Pruni Semen", "nature": "平", "flavor": ["辛", "苦", "甘"], "meridian": ["大肠经", "小肠经"], "effects": ["润肠通便", "利水消肿"], "indications": ["肠燥便秘", "水肿"], "usage": "煎服，6-12g", "contraindications": ["孕妇慎用"], "category": "泻下药", "subcategory": "润下药"},
        {"name": "松子仁", "pinyin": "Song Zi Ren", "latin_name": "Pini Kernel", "nature": "温", "flavor": ["甘"], "meridian": ["肺经", "大肠经"], "effects": ["润肠通便", "润肺止咳"], "indications": ["肠燥便秘", "肺燥咳嗽"], "usage": "煎服，10-15g", "contraindications": ["脾虚便溏者慎用"], "category": "泻下药", "subcategory": "润下药"},
        {"name": "川乌", "pinyin": "Chuan Wu", "latin_name": "Aconiti Radix", "nature": "热", "flavor": ["辛", "苦"], "meridian": ["心经", "肝经", "肾经", "脾经"], "effects": ["祛风湿", "温经止痛"], "indications": ["风寒湿痹", "心腹冷痛"], "usage": "煎服，1.5-3g，先煎", "contraindications": ["孕妇禁用"], "category": "祛风湿药", "subcategory": "祛风湿散寒药"},
        {"name": "草乌", "pinyin": "Cao Wu", "latin_name": "Aconiti Kusnezoffii Radix", "nature": "热", "flavor": ["辛", "苦"], "meridian": ["心经", "肝经", "肾经", "脾经"], "effects": ["祛风湿", "温经止痛"], "indications": ["风寒湿痹", "跌打损伤"], "usage": "煎服，1.5-3g，先煎", "contraindications": ["孕妇禁用"], "category": "祛风湿药", "subcategory": "祛风湿散寒药"},
        {"name": "蕲蛇", "pinyin": "Qi She", "latin_name": "Agkistrodon", "nature": "温", "flavor": ["甘", "咸"], "meridian": ["肝经"], "effects": ["祛风", "通络", "止痉"], "indications": ["风湿顽痹", "小儿惊风"], "usage": "煎服，3-9g", "contraindications": ["阴虚内热者慎用"], "category": "祛风湿药", "subcategory": "祛风湿散寒药"},
        {"name": "乌梢蛇", "pinyin": "Wu Shao She", "latin_name": "Zaocys", "nature": "平", "flavor": ["甘"], "meridian": ["肝经"], "effects": ["祛风", "通络", "止痉"], "indications": ["风湿顽痹", "皮肤瘙痒"], "usage": "煎服，9-12g", "contraindications": [], "category": "祛风湿药", "subcategory": "祛风湿散寒药"},
        {"name": "防己", "pinyin": "Fang Ji", "latin_name": "Stephaniae Radix", "nature": "寒", "flavor": ["苦", "辛"], "meridian": ["膀胱经", "肺经"], "effects": ["祛风湿", "止痛", "利水消肿"], "indications": ["风湿痹痛", "水肿"], "usage": "煎服，4.5-9g", "contraindications": ["脾胃虚寒者慎用"], "category": "祛风湿药", "subcategory": "祛风湿清热药"},
        {"name": "桑枝", "pinyin": "Sang Zhi", "latin_name": "Mori Ramulus", "nature": "平", "flavor": ["苦"], "meridian": ["肝经"], "effects": ["祛风湿", "利关节"], "indications": ["风湿痹痛", "四肢拘挛"], "usage": "煎服，9-15g", "contraindications": [], "category": "祛风湿药", "subcategory": "祛风湿清热药"},
        {"name": "豨莶草", "pinyin": "Xi Xian Cao", "latin_name": "Siegesbeckiae Herba", "nature": "寒", "flavor": ["辛", "苦"], "meridian": ["肝经", "肾经"], "effects": ["祛风湿", "利关节", "解毒"], "indications": ["风湿痹痛", "湿疹瘙痒"], "usage": "煎服，9-12g", "contraindications": [], "category": "祛风湿药", "subcategory": "祛风湿清热药"},
        {"name": "臭梧桐", "pinyin": "Chou Wu Tong", "latin_name": "Clerodendri Folium", "nature": "平", "flavor": ["辛", "苦"], "meridian": ["肝经"], "effects": ["祛风湿", "通经络", "平肝"], "indications": ["风湿痹痛", "头痛眩晕"], "usage": "煎服，5-15g", "contraindications": [], "category": "祛风湿药", "subcategory": "祛风湿清热药"},
        {"name": "海桐皮", "pinyin": "Hai Tong Pi", "latin_name": "Erythrinae Cortex", "nature": "平", "flavor": ["苦", "辛"], "meridian": ["肝经"], "effects": ["祛风湿", "通络止痛", "杀虫止痒"], "indications": ["风湿痹痛", "疥癣瘙痒"], "usage": "煎服，6-12g", "contraindications": [], "category": "祛风湿药", "subcategory": "祛风湿清热药"},
        {"name": "络石藤", "pinyin": "Luo Shi Teng", "latin_name": "Trachelospermi Caulis", "nature": "微寒", "flavor": ["苦"], "meridian": ["心经", "肝经"], "effects": ["祛风通络", "凉血消肿"], "indications": ["风湿热痹", "喉痹"], "usage": "煎服，6-12g", "contraindications": [], "category": "祛风湿药", "subcategory": "祛风湿清热药"},
        {"name": "雷公藤", "pinyin": "Lei Gong Teng", "latin_name": "Tripterygii Radix", "nature": "凉", "flavor": ["苦"], "meridian": ["肝经"], "effects": ["祛风除湿", "活血通络", "消肿止痛"], "indications": ["风湿顽痹", "疔疮肿毒"], "usage": "煎服，1-2g", "contraindications": ["孕妇禁用"], "category": "祛风湿药", "subcategory": "祛风湿清热药"},
        {"name": "狗脊", "pinyin": "Gou Ji", "latin_name": "Cibotii Rhizoma", "nature": "温", "flavor": ["苦", "甘"], "meridian": ["肝经", "肾经"], "effects": ["祛风湿", "补肝肾", "强腰膝"], "indications": ["风湿痹痛", "腰膝酸软"], "usage": "煎服，6-12g", "contraindications": [], "category": "祛风湿药", "subcategory": "祛风湿强筋骨药"},
        {"name": "千年健", "pinyin": "Qian Nian Jian", "latin_name": "Homalomenae Rhizoma", "nature": "温", "flavor": ["苦", "辛"], "meridian": ["肝经", "肾经"], "effects": ["祛风湿", "强筋骨"], "indications": ["风湿痹痛", "腰膝酸软"], "usage": "煎服，4.5-9g", "contraindications": [], "category": "祛风湿药", "subcategory": "祛风湿强筋骨药"},
        {"name": "佩兰", "pinyin": "Pei Lan", "latin_name": "Eupatorii Herba", "nature": "平", "flavor": ["辛"], "meridian": ["脾经", "胃经", "肺经"], "effects": ["化湿", "解暑"], "indications": ["湿阻中焦", "暑湿"], "usage": "煎服，5-10g", "contraindications": [], "category": "化湿药", "subcategory": ""},
        {"name": "砂仁", "pinyin": "Sha Ren", "latin_name": "Amomi Fructus", "nature": "温", "flavor": ["辛"], "meridian": ["脾经", "胃经", "肾经"], "effects": ["化湿开胃", "温脾止泻", "理气安胎"], "indications": ["湿阻中焦", "脾胃虚寒"], "usage": "煎服，3-6g，后下", "contraindications": [], "category": "化湿药", "subcategory": ""},
        {"name": "豆蔻", "pinyin": "Dou Kou", "latin_name": "Amomi Rotundus Fructus", "nature": "温", "flavor": ["辛"], "meridian": ["脾经", "胃经"], "effects": ["化湿行气", "温中止呕"], "indications": ["湿阻中焦", "呕吐"], "usage": "煎服，3-6g，后下", "contraindications": [], "category": "化湿药", "subcategory": ""},
        {"name": "草豆蔻", "pinyin": "Cao Dou Kou", "latin_name": "Alpiniae Semen", "nature": "温", "flavor": ["辛"], "meridian": ["脾经", "胃经"], "effects": ["燥湿行气", "温中止呕"], "indications": ["寒湿阻滞", "呕吐"], "usage": "煎服，3-6g", "contraindications": [], "category": "化湿药", "subcategory": ""},
        {"name": "草果", "pinyin": "Cao Guo", "latin_name": "Tsaoko Fructus", "nature": "温", "flavor": ["辛"], "meridian": ["脾经", "胃经"], "effects": ["燥湿温中", "除痰截疟"], "indications": ["寒湿阻滞", "疟疾"], "usage": "煎服，3-6g", "contraindications": [], "category": "化湿药", "subcategory": ""},
        {"name": "冬瓜皮", "pinyin": "Dong Gua Pi", "latin_name": "Benincasae Exocarpium", "nature": "凉", "flavor": ["甘"], "meridian": ["脾经", "小肠经"], "effects": ["利水消肿", "清热解暑"], "indications": ["水肿", "暑热"], "usage": "煎服，9-30g", "contraindications": [], "category": "利水渗湿药", "subcategory": "利水消肿药"},
        {"name": "通草", "pinyin": "Tong Cao", "latin_name": "Tetrapanacis Medulla", "nature": "微寒", "flavor": ["甘", "淡"], "meridian": ["肺经", "胃经"], "effects": ["清热利尿", "通气下乳"], "indications": ["湿热淋证", "乳汁不下"], "usage": "煎服，3-5g", "contraindications": ["孕妇慎用"], "category": "利水渗湿药", "subcategory": "利尿通淋药"},
        {"name": "瞿麦", "pinyin": "Qu Mai", "latin_name": "Dianthi Herba", "nature": "寒", "flavor": ["苦"], "meridian": ["心经", "小肠经"], "effects": ["利尿通淋", "破血通经"], "indications": ["热淋涩痛", "闭经"], "usage": "煎服，9-15g", "contraindications": ["孕妇慎用"], "category": "利水渗湿药", "subcategory": "利尿通淋药"},
        {"name": "扁蓄", "pinyin": "Bian Xu", "latin_name": "Polygonavinis Herba", "nature": "微寒", "flavor": ["苦"], "meridian": ["膀胱经"], "effects": ["利尿通淋", "杀虫止痒"], "indications": ["热淋涩痛", "皮肤湿疹"], "usage": "煎服，9-15g", "contraindications": [], "category": "利水渗湿药", "subcategory": "利尿通淋药"},
        {"name": "海金沙", "pinyin": "Hai Jin Sha", "latin_name": "Lygodii Spora", "nature": "寒", "flavor": ["甘", "咸"], "meridian": ["膀胱经", "小肠经"], "effects": ["利尿通淋", "止痛"], "indications": ["热淋涩痛"], "usage": "煎服，6-15g，包煎", "contraindications": [], "category": "利水渗湿药", "subcategory": "利尿通淋药"},
        {"name": "石韦", "pinyin": "Shi Wei", "latin_name": "Pyrrosiae Folium", "nature": "微寒", "flavor": ["甘", "苦"], "meridian": ["肺经", "膀胱经"], "effects": ["利尿通淋", "清肺止咳"], "indications": ["热淋涩痛", "肺热咳嗽"], "usage": "煎服，6-12g", "contraindications": [], "category": "利水渗湿药", "subcategory": "利尿通淋药"},
        {"name": "金钱草", "pinyin": "Jin Qian Cao", "latin_name": "Lysimachiae Herba", "nature": "微寒", "flavor": ["甘", "咸"], "meridian": ["肝经", "胆经", "肾经", "膀胱经"], "effects": ["利湿退黄", "利尿通淋", "解毒消肿"], "indications": ["黄疸", "石淋"], "usage": "煎服，15-60g", "contraindications": [], "category": "利水渗湿药", "subcategory": "利湿退黄药"},
        {"name": "花椒", "pinyin": "Hua Jiao", "latin_name": "Zanthoxyli Pericarpium", "nature": "温", "flavor": ["辛"], "meridian": ["脾经", "胃经", "肾经"], "effects": ["温中止痛", "杀虫止痒"], "indications": ["脘腹冷痛", "湿疹瘙痒"], "usage": "煎服，3-6g", "contraindications": [], "category": "温里药", "subcategory": ""},
        {"name": "丁香", "pinyin": "Ding Xiang", "latin_name": "Caryophylli Flos", "nature": "温", "flavor": ["辛"], "meridian": ["脾经", "胃经", "肺经", "肾经"], "effects": ["温中降逆", "散寒止痛", "温肾助阳"], "indications": ["呕吐呃逆", "阳痿"], "usage": "煎服，1-3g", "contraindications": [], "category": "温里药", "subcategory": ""},
        {"name": "青皮", "pinyin": "Qing Pi", "latin_name": "Citri Viride Pericarpium", "nature": "温", "flavor": ["苦", "辛"], "meridian": ["肝经", "胆经", "胃经"], "effects": ["疏肝破气", "消积化滞"], "indications": ["肝郁气滞", "食积气滞"], "usage": "煎服，3-10g", "contraindications": [], "category": "理气药", "subcategory": ""},
        {"name": "沉香", "pinyin": "Chen Xiang", "latin_name": "Aquilariae Lignum", "nature": "微温", "flavor": ["辛", "苦"], "meridian": ["脾经", "胃经", "肾经"], "effects": ["行气止痛", "温中止呕", "纳气平喘"], "indications": ["胸腹胀痛", "呕吐"], "usage": "煎服，1-5g，后下", "contraindications": [], "category": "理气药", "subcategory": ""},
        {"name": "檀香", "pinyin": "Tan Xiang", "latin_name": "Santali Albi Lignum", "nature": "温", "flavor": ["辛"], "meridian": ["脾经", "胃经", "肺经"], "effects": ["行气止痛", "散寒调中"], "indications": ["寒凝气滞", "胸腹冷痛"], "usage": "煎服，1-3g，后下", "contraindications": [], "category": "理气药", "subcategory": ""},
        {"name": "乌药", "pinyin": "Wu Yao", "latin_name": "Linderae Radix", "nature": "温", "flavor": ["辛"], "meridian": ["脾经", "肺经", "肾经", "膀胱经"], "effects": ["行气止痛", "温肾散寒"], "indications": ["寒凝气滞", "尿频遗尿"], "usage": "煎服，6-10g", "contraindications": [], "category": "理气药", "subcategory": ""},
        {"name": "荔枝核", "pinyin": "Li Zhi He", "latin_name": "Litchi Semen", "nature": "温", "flavor": ["甘", "微苦"], "meridian": ["肝经", "肾经"], "effects": ["行气散结", "散寒止痛"], "indications": ["寒疝腹痛", "睾丸肿痛"], "usage": "煎服，5-10g", "contraindications": [], "category": "理气药", "subcategory": ""},
        {"name": "川楝子", "pinyin": "Chuan Lian Zi", "latin_name": "Toosendan Fructus", "nature": "寒", "flavor": ["苦"], "meridian": ["肝经"], "effects": ["行气止痛", "杀虫"], "indications": ["肝郁化火", "虫积腹痛"], "usage": "煎服，5-10g", "contraindications": ["脾胃虚寒者慎用"], "category": "理气药", "subcategory": ""},
        {"name": "神曲", "pinyin": "Shen Qu", "latin_name": "Massa Medicata Fermentata", "nature": "温", "flavor": ["甘", "辛"], "meridian": ["脾经", "胃经"], "effects": ["消食化积", "健脾和胃"], "indications": ["饮食积滞"], "usage": "煎服，6-15g", "contraindications": [], "category": "消食药", "subcategory": ""},
        {"name": "谷芽", "pinyin": "Gu Ya", "latin_name": "Oryzae Fructus Germinatus", "nature": "平", "flavor": ["甘"], "meridian": ["脾经", "胃经"], "effects": ["消食和中", "健脾开胃"], "indications": ["米面薯芋食滞"], "usage": "煎服，9-15g", "contraindications": [], "category": "消食药", "subcategory": ""},
        {"name": "槐花", "pinyin": "Huai Hua", "latin_name": "Sophorae Flavescentis", "nature": "微寒", "flavor": ["苦"], "meridian": ["肝经", "大肠经"], "effects": ["凉血止血", "清肝泻火"], "indications": ["血热出血", "目赤肿痛"], "usage": "煎服，6-12g", "contraindications": [], "category": "止血药", "subcategory": "凉血止血药"},
        {"name": "侧柏叶", "pinyin": "Ce Bai Ye", "latin_name": "Platycladi Cacumen", "nature": "寒", "flavor": ["苦", "涩"], "meridian": ["肺经", "肝经", "脾经"], "effects": ["凉血止血", "化痰止咳"], "indications": ["血热出血", "肺热咳嗽"], "usage": "煎服，6-12g", "contraindications": [], "category": "止血药", "subcategory": "凉血止血药"},
        {"name": "白茅根", "pinyin": "Bai Mao Gen", "latin_name": "Imperatae Rhizoma", "nature": "寒", "flavor": ["甘"], "meridian": ["肺经", "胃经", "膀胱经"], "effects": ["凉血止血", "清热利尿"], "indications": ["血热出血", "热淋"], "usage": "煎服，9-30g", "contraindications": [], "category": "止血药", "subcategory": "凉血止血药"},
        {"name": "蒲黄", "pinyin": "Pu Huang", "latin_name": "Typhae Pollen", "nature": "平", "flavor": ["甘"], "meridian": ["肝经", "心包经"], "effects": ["止血", "化瘀", "利尿"], "indications": ["出血证", "瘀血痛证"], "usage": "煎服，5-10g，包煎", "contraindications": ["孕妇慎用"], "category": "止血药", "subcategory": "化瘀止血药"},
        {"name": "仙鹤草", "pinyin": "Xian He Cao", "latin_name": "Agrimoniae Herba", "nature": "平", "flavor": ["苦", "涩"], "meridian": ["心经", "肝经"], "effects": ["收敛止血", "止痢", "截疟"], "indications": ["出血证", "腹泻"], "usage": "煎服，6-12g", "contraindications": [], "category": "止血药", "subcategory": "收敛止血药"},
        {"name": "棕榈炭", "pinyin": "Zong Lu Tan", "latin_name": "Trachycarpi Carbonisatus", "nature": "平", "flavor": ["苦", "涩"], "meridian": ["肝经", "肺经", "大肠经"], "effects": ["收敛止血"], "indications": ["出血证"], "usage": "煎服，3-10g", "contraindications": [], "category": "止血药", "subcategory": "收敛止血药"},
        {"name": "血余炭", "pinyin": "Xue Yu Tan", "latin_name": "Crinis Carbonisatus", "nature": "平", "flavor": ["苦"], "meridian": ["肝经", "胃经"], "effects": ["收敛止血", "化瘀", "利尿"], "indications": ["出血证", "小便不利"], "usage": "煎服，6-10g", "contraindications": [], "category": "止血药", "subcategory": "收敛止血药"},
        {"name": "艾叶", "pinyin": "Ai Ye", "latin_name": "Artemisiae Argyi Folium", "nature": "温", "flavor": ["苦", "辛"], "meridian": ["肝经", "脾经", "肾经"], "effects": ["温经止血", "散寒调经", "安胎"], "indications": ["出血证", "月经不调"], "usage": "煎服，3-9g", "contraindications": [], "category": "止血药", "subcategory": "温经止血药"},
        {"name": "炮姜", "pinyin": "Pao Jiang", "latin_name": "Zingiberis Rhizoma", "nature": "热", "flavor": ["苦", "辛"], "meridian": ["脾经", "肝经"], "effects": ["温经止血", "温中止痛"], "indications": ["出血证", "腹痛"], "usage": "煎服，3-9g", "contraindications": [], "category": "止血药", "subcategory": "温经止血药"},
        {"name": "川芎", "pinyin": "Chuan Xiong", "latin_name": "Chuanxiong Rhizoma", "nature": "温", "flavor": ["辛"], "meridian": ["肝经", "胆经", "心包经"], "effects": ["活血行气", "祛风止痛"], "indications": ["血瘀气滞", "头痛"], "usage": "煎服，3-9g", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血止痛药"},
        {"name": "延胡索", "pinyin": "Yan Hu Suo", "latin_name": "Corydalis Rhizoma", "nature": "温", "flavor": ["辛", "苦"], "meridian": ["肝经", "脾经"], "effects": ["活血行气止痛"], "indications": ["气滞血瘀"], "usage": "煎服，3-10g", "contraindications": [], "category": "活血化瘀药", "subcategory": "活血止痛药"},
        {"name": "郁金", "pinyin": "Yu Jin", "latin_name": "Curcumae Radix", "nature": "寒", "flavor": ["辛", "苦"], "meridian": ["肝经", "胆经", "心经"], "effects": ["活血止痛", "行气解郁", "清心凉血"], "indications": ["血瘀气滞", "热病神昏"], "usage": "煎服，5-12g", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血止痛药"},
        {"name": "姜黄", "pinyin": "Jiang Huang", "latin_name": "Curcumae Longae Rhizoma", "nature": "温", "flavor": ["辛", "苦"], "meridian": ["肝经", "脾经"], "effects": ["破血行气", "通经止痛"], "indications": ["血瘀气滞", "风湿痹痛"], "usage": "煎服，3-10g", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血止痛药"},
        {"name": "乳香", "pinyin": "Ru Xiang", "latin_name": "Boswellia", "nature": "温", "flavor": ["辛", "苦"], "meridian": ["心经", "肝经", "脾经"], "effects": ["活血行气止痛", "消肿生肌"], "indications": ["瘀血阻滞", "疮疡痈肿"], "usage": "煎服，3-10g", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血止痛药"},
        {"name": "没药", "pinyin": "Mo Yao", "latin_name": "Myrrha", "nature": "平", "flavor": ["辛", "苦"], "meridian": ["心经", "肝经", "脾经"], "effects": ["活血止痛", "消肿生肌"], "indications": ["瘀血阻滞", "疮疡痈肿"], "usage": "煎服，3-10g", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血止痛药"},
        {"name": "红花", "pinyin": "Hong Hua", "latin_name": "Carthami Flos", "nature": "温", "flavor": ["辛"], "meridian": ["心经", "肝经"], "effects": ["活血通经", "祛瘀止痛"], "indications": ["血滞经闭", "瘀滞肿痛"], "usage": "煎服，3-10g", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血调经药"},
        {"name": "桃仁", "pinyin": "Tao Ren", "latin_name": "Persicae Semen", "nature": "平", "flavor": ["苦", "甘"], "meridian": ["心经", "肝经", "大肠经"], "effects": ["活血祛瘀", "润肠通便"], "indications": ["瘀血阻滞", "肠燥便秘"], "usage": "煎服，5-10g", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血调经药"},
        {"name": "益母草", "pinyin": "Yi Mu Cao", "latin_name": "Leonuri Herba", "nature": "微寒", "flavor": ["苦", "辛"], "meridian": ["肝经", "心包经"], "effects": ["活血调经", "利尿消肿"], "indications": ["月经不调", "水肿"], "usage": "煎服，9-30g", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血调经药"},
        {"name": "泽兰", "pinyin": "Ze Lan", "latin_name": "Lycopi Herba", "nature": "微温", "flavor": ["苦", "辛"], "meridian": ["肝经", "脾经"], "effects": ["活血调经", "利水消肿"], "indications": ["月经不调", "水肿"], "usage": "煎服，6-12g", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血调经药"},
        {"name": "牛膝", "pinyin": "Niu Xi", "latin_name": "Achyranthis Bidentatae Radix", "nature": "平", "flavor": ["苦", "甘", "酸"], "meridian": ["肝经", "肾经"], "effects": ["活血通经", "补肝肾", "强筋骨"], "indications": ["瘀血阻滞", "腰膝酸软"], "usage": "煎服，6-15g", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血调经药"},
        {"name": "鸡血藤", "pinyin": "Ji Xue Teng", "latin_name": "Spatholobi Caulis", "nature": "温", "flavor": ["苦", "甘"], "meridian": ["肝经"], "effects": ["行血补血", "调经", "舒筋活络"], "indications": ["月经不调", "风湿痹痛"], "usage": "煎服，9-15g", "contraindications": [], "category": "活血化瘀药", "subcategory": "活血调经药"},
        {"name": "王不留行", "pinyin": "Wang Bu Liu Xing", "latin_name": "Vaccariae Semen", "nature": "平", "flavor": ["苦"], "meridian": ["肝经", "胃经"], "effects": ["活血通经", "下乳消肿"], "indications": ["血瘀经闭", "乳汁不下"], "usage": "煎服，5-10g", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血调经药"},
        {"name": "月季花", "pinyin": "Yue Ji Hua", "latin_name": "Rosae Chinensis Flos", "nature": "温", "flavor": ["甘"], "meridian": ["肝经"], "effects": ["活血调经", "疏肝理气"], "indications": ["月经不调", "胸胁胀痛"], "usage": "煎服，2-5g", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血调经药"},
        {"name": "凌霄花", "pinyin": "Ling Xiao Hua", "latin_name": "Campsis Flos", "nature": "微寒", "flavor": ["辛"], "meridian": ["肝经"], "effects": ["破瘀通经", "凉血祛风"], "indications": ["血瘀经闭", "风疹瘙痒"], "usage": "煎服，5-9g", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血调经药"},
        {"name": "自然铜", "pinyin": "Zi Ran Tong", "latin_name": "Pyritum", "nature": "平", "flavor": ["辛"], "meridian": ["肝经"], "effects": ["散瘀止痛", "接骨疗伤"], "indications": ["跌打损伤", "筋骨折伤"], "usage": "煎服，10-15g", "contraindications": [], "category": "活血化瘀药", "subcategory": "活血疗伤药"},
        {"name": "苏木", "pinyin": "Su Mu", "latin_name": "Sappan Lignum", "nature": "平", "flavor": ["甘", "咸"], "meridian": ["心经", "肝经"], "effects": ["活血疗伤", "祛瘀通经"], "indications": ["跌打损伤", "血瘀经闭"], "usage": "煎服，3-10g", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血疗伤药"},
        {"name": "骨碎补", "pinyin": "Gu Sui Bu", "latin_name": "Drynariae Rhizoma", "nature": "温", "flavor": ["苦"], "meridian": ["肝经", "肾经"], "effects": ["活血续伤", "补肾强骨"], "indications": ["跌打损伤", "肾虚腰痛"], "usage": "煎服，10-15g", "contraindications": [], "category": "活血化瘀药", "subcategory": "活血疗伤药"},
        {"name": "血竭", "pinyin": "Xue Jie", "latin_name": "Draconis Sanguis", "nature": "平", "flavor": ["甘", "咸"], "meridian": ["心经", "肝经"], "effects": ["活血定痛", "化瘀止血", "敛疮生肌"], "indications": ["瘀血阻滞", "出血证"], "usage": "1-2g，入丸散", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血疗伤药"},
        {"name": "儿茶", "pinyin": "Er Cha", "latin_name": "Catechu", "nature": "微寒", "flavor": ["苦", "涩"], "meridian": ["肺经", "心经"], "effects": ["活血疗伤", "止血生肌", "收湿敛疮"], "indications": ["跌打损伤", "疮疡不敛"], "usage": "1-3g，入丸散", "contraindications": [], "category": "活血化瘀药", "subcategory": "活血疗伤药"},
        {"name": "刘寄奴", "pinyin": "Liu Ji Nu", "latin_name": "Artemisiae Anomalae Herba", "nature": "温", "flavor": ["苦"], "meridian": ["心经", "肝经"], "effects": ["散瘀止痛", "疗伤止血", "破血通经"], "indications": ["跌打损伤", "血瘀经闭"], "usage": "煎服，6-10g", "contraindications": ["孕妇慎用"], "category": "活血化瘀药", "subcategory": "活血疗伤药"},
        {"name": "水蛭", "pinyin": "Shui Zhi", "latin_name": "Hirudo", "nature": "平", "flavor": ["咸", "苦"], "meridian": ["肝经"], "effects": ["破血通经", "逐瘀消癥"], "indications": ["血瘀经闭", "癥瘕积聚"], "usage": "煎服，1-3g", "contraindications": ["孕妇禁用"], "category": "活血化瘀药", "subcategory": "破血消癥药"},
        {"name": "虻虫", "pinyin": "Meng Chong", "latin_name": "Tabanus", "nature": "微寒", "flavor": ["苦"], "meridian": ["肝经"], "effects": ["破血逐瘀", "散积消癥"], "indications": ["血瘀经闭", "癥瘕积聚"], "usage": "煎服，1-1.5g", "contraindications": ["孕妇禁用"], "category": "活血化瘀药", "subcategory": "破血消癥药"},
        {"name": "斑蝥", "pinyin": "Ban Mao", "latin_name": "Mylabris", "nature": "热", "flavor": ["辛"], "meridian": ["肝经"], "effects": ["破血逐瘀", "散结消癥", "攻毒蚀疮"], "indications": ["癥瘕积聚", "痈疽恶疮"], "usage": "0.03-0.06g，入丸散", "contraindications": ["孕妇禁用"], "category": "活血化瘀药", "subcategory": "破血消癥药"},
        {"name": "半夏", "pinyin": "Ban Xia", "latin_name": "Pinelliae Rhizoma", "nature": "温", "flavor": ["辛"], "meridian": ["脾经", "胃经", "肺经"], "effects": ["燥湿化痰", "降逆止呕", "消痞散结"], "indications": ["痰湿咳嗽", "呕吐"], "usage": "煎服，3-9g", "contraindications": ["孕妇慎用"], "category": "化痰止咳平喘药", "subcategory": "温化寒痰药"},
        {"name": "天南星", "pinyin": "Tian Nan Xing", "latin_name": "Arisaematis Rhizoma", "nature": "温", "flavor": ["苦", "辛"], "meridian": ["肺经", "肝经", "脾经"], "effects": ["燥湿化痰", "祛风解痉"], "indications": ["痰湿咳嗽", "风痰眩晕"], "usage": "煎服，3-9g", "contraindications": ["孕妇慎用"], "category": "化痰止咳平喘药", "subcategory": "温化寒痰药"},
        {"name": "禹白附", "pinyin": "Yu Bai Fu", "latin_name": "Typhonii Rhizoma", "nature": "温", "flavor": ["辛", "甘"], "meridian": ["胃经", "肝经"], "effects": ["祛风痰", "定惊搐", "解毒散结"], "indications": ["中风痰壅", "惊风癫痫"], "usage": "煎服，3-5g", "contraindications": ["孕妇慎用"], "category": "化痰止咳平喘药", "subcategory": "温化寒痰药"},
        {"name": "白芥子", "pinyin": "Bai Jie Zi", "latin_name": "Sinapis Semen", "nature": "温", "flavor": ["辛"], "meridian": ["肺经"], "effects": ["温肺化痰", "利气散结"], "indications": ["寒痰咳嗽", "阴疽流注"], "usage": "煎服，3-9g", "contraindications": ["肺虚久咳者慎用"], "category": "化痰止咳平喘药", "subcategory": "温化寒痰药"},
        {"name": "皂荚", "pinyin": "Zao Jia", "latin_name": "Gleditsiae Fructus", "nature": "温", "flavor": ["辛", "咸"], "meridian": ["肺经", "大肠经"], "effects": ["祛顽痰", "通窍开闭"], "indications": ["顽痰阻肺", "痰厥"], "usage": "煎服，1-1.5g", "contraindications": ["孕妇禁用"], "category": "化痰止咳平喘药", "subcategory": "温化寒痰药"},
        {"name": "旋覆花", "pinyin": "Xuan Fu Hua", "latin_name": "Inulae Flos", "nature": "微温", "flavor": ["苦", "辛", "咸"], "meridian": ["肺经", "胃经"], "effects": ["降气化痰", "降逆止呕"], "indications": ["咳嗽痰多", "呕吐"], "usage": "煎服，3-10g，包煎", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "温化寒痰药"},
        {"name": "川贝母", "pinyin": "Chuan Bei Mu", "latin_name": "Fritillariae Cirrhosae Bulbus", "nature": "微寒", "flavor": ["甘", "苦"], "meridian": ["肺经", "心经"], "effects": ["清热润肺", "化痰止咳", "散结消痈"], "indications": ["肺热燥咳", "瘰疬"], "usage": "煎服，3-10g", "contraindications": ["脾胃虚寒者慎用"], "category": "化痰止咳平喘药", "subcategory": "清热化痰药"},
        {"name": "浙贝母", "pinyin": "Zhe Bei Mu", "latin_name": "Fritillariae Thunbergii Bulbus", "nature": "寒", "flavor": ["苦"], "meridian": ["肺经", "心经"], "effects": ["清热化痰", "散结消痈"], "indications": ["风热痰热咳嗽", "疮痈"], "usage": "煎服，5-10g", "contraindications": ["脾胃虚寒者慎用"], "category": "化痰止咳平喘药", "subcategory": "清热化痰药"},
        {"name": "瓜蒌", "pinyin": "Gua Lou", "latin_name": "Trichosanthis Fructus", "nature": "寒", "flavor": ["甘", "微苦"], "meridian": ["肺经", "胃经", "大肠经"], "effects": ["清热化痰", "宽胸散结", "润肠通便"], "indications": ["肺热咳嗽", "胸痹"], "usage": "煎服，9-15g", "contraindications": ["脾虚便溏者慎用"], "category": "化痰止咳平喘药", "subcategory": "清热化痰药"},
        {"name": "竹茹", "pinyin": "Zhu Ru", "latin_name": "Bambusae Caulis", "nature": "微寒", "flavor": ["甘"], "meridian": ["肺经", "胃经"], "effects": ["清热化痰", "除烦止呕"], "indications": ["肺热咳嗽", "呕吐"], "usage": "煎服，6-10g", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "清热化痰药"},
        {"name": "竹沥", "pinyin": "Zhu Li", "latin_name": "Bambusae Succus", "nature": "寒", "flavor": ["甘"], "meridian": ["心经", "肺经", "肝经"], "effects": ["清热豁痰", "定惊利窍"], "indications": ["痰热咳喘", "中风痰迷"], "usage": "冲服，30-60g", "contraindications": ["脾胃虚寒者慎用"], "category": "化痰止咳平喘药", "subcategory": "清热化痰药"},
        {"name": "天竺黄", "pinyin": "Tian Zhu Huang", "latin_name": "Bambusae Concretio", "nature": "寒", "flavor": ["甘"], "meridian": ["心经", "肝经"], "effects": ["清热化痰", "清心定惊"], "indications": ["小儿惊风", "中风痰迷"], "usage": "煎服，3-6g", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "清热化痰药"},
        {"name": "前胡", "pinyin": "Qian Hu", "latin_name": "Peucedani Radix", "nature": "微寒", "flavor": ["苦", "辛"], "meridian": ["肺经"], "effects": ["降气化痰", "疏散风热"], "indications": ["痰热咳嗽", "风热感冒"], "usage": "煎服，6-10g", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "清热化痰药"},
        {"name": "桔梗", "pinyin": "Jie Geng", "latin_name": "Platycodonis Radix", "nature": "平", "flavor": ["苦", "辛"], "meridian": ["肺经"], "effects": ["宣肺", "利咽", "祛痰"], "indications": ["咳嗽痰多", "咽痛"], "usage": "煎服，3-10g", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "清热化痰药"},
        {"name": "胖大海", "pinyin": "Pang Da Hai", "latin_name": "Sterculiae Lychnophorae Semen", "nature": "寒", "flavor": ["甘"], "meridian": ["肺经", "大肠经"], "effects": ["清热润肺", "利咽解毒", "润肠通便"], "indications": ["肺热声嘶", "便秘"], "usage": "2-4枚，泡服", "contraindications": ["脾胃虚寒者慎用"], "category": "化痰止咳平喘药", "subcategory": "清热化痰药"},
        {"name": "海藻", "pinyin": "Hai Zao", "latin_name": "Sargassum", "nature": "寒", "flavor": ["苦", "咸"], "meridian": ["肝经", "胃经", "肾经"], "effects": ["消痰软坚", "利水消肿"], "indications": ["瘿瘤", "痰饮水肿"], "usage": "煎服，10-15g", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "消痰软坚药"},
        {"name": "昆布", "pinyin": "Kun Bu", "latin_name": "Thallus Laminariae", "nature": "寒", "flavor": ["咸"], "meridian": ["肝经", "胃经", "肾经"], "effects": ["消痰软坚", "利水消肿"], "indications": ["瘿瘤", "痰饮水肿"], "usage": "煎服，6-12g", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "消痰软坚药"},
        {"name": "黄药子", "pinyin": "Huang Yao Zi", "latin_name": "Dioscoreae Bulbus", "nature": "寒", "flavor": ["苦"], "meridian": ["肺经", "肝经"], "effects": ["化痰散结消瘿", "清热解毒"], "indications": ["瘿瘤", "疮痈"], "usage": "煎服，5-15g", "contraindications": ["脾胃虚寒者慎用"], "category": "化痰止咳平喘药", "subcategory": "消痰软坚药"},
        {"name": "海蛤壳", "pinyin": "Hai Ge Ke", "latin_name": "Concha Meretricis", "nature": "寒", "flavor": ["咸"], "meridian": ["肺经", "胃经"], "effects": ["清肺化痰", "软坚散结"], "indications": ["肺热痰稠", "瘿瘤"], "usage": "煎服，10-15g", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "消痰软坚药"},
        {"name": "海浮石", "pinyin": "Hai Fu Shi", "latin_name": "Pumice", "nature": "寒", "flavor": ["咸"], "meridian": ["肺经"], "effects": ["清肺化痰", "软坚散结"], "indications": ["肺热痰稠", "瘿瘤"], "usage": "煎服，10-15g", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "消痰软坚药"},
        {"name": "瓦楞子", "pinyin": "Wa Leng Zi", "latin_name": "Concha Arcae", "nature": "平", "flavor": ["咸"], "meridian": ["肺经", "胃经", "肝经"], "effects": ["消痰软坚", "化瘀散结"], "indications": ["瘿瘤", "癥瘕"], "usage": "煎服，10-15g", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "消痰软坚药"},
        {"name": "杏仁", "pinyin": "Xing Ren", "latin_name": "Armeniacae Semen", "nature": "温", "flavor": ["苦"], "meridian": ["肺经", "大肠经"], "effects": ["止咳平喘", "润肠通便"], "indications": ["咳嗽气喘", "肠燥便秘"], "usage": "煎服，6-10g", "contraindications": ["阴虚咳嗽者慎用"], "category": "化痰止咳平喘药", "subcategory": "止咳平喘药"},
        {"name": "紫苏子", "pinyin": "Zi Su Zi", "latin_name": "Perillae Semen", "nature": "温", "flavor": ["辛", "温"], "meridian": ["肺经", "大肠经"], "effects": ["降气化痰", "止咳平喘", "润肠通便"], "indications": ["痰壅气逆", "肠燥便秘"], "usage": "煎服，6-10g", "contraindications": ["阴虚喘咳者慎用"], "category": "化痰止咳平喘药", "subcategory": "止咳平喘药"},
        {"name": "百部", "pinyin": "Bai Bu", "latin_name": "Stemonae Radix", "nature": "微温", "flavor": ["甘", "苦"], "meridian": ["肺经"], "effects": ["润肺下气止咳", "杀虫"], "indications": ["新久咳嗽", "肺痨咳嗽"], "usage": "煎服，3-9g", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "止咳平喘药"},
        {"name": "紫菀", "pinyin": "Zi Wan", "latin_name": "Asteris Radix", "nature": "温", "flavor": ["辛", "甘"], "meridian": ["肺经"], "effects": ["润肺化痰止咳"], "indications": ["咳嗽有痰"], "usage": "煎服，6-10g", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "止咳平喘药"},
        {"name": "款冬花", "pinyin": "Kuan Dong Hua", "latin_name": "Farfarae Flos", "nature": "温", "flavor": ["辛", "微苦"], "meridian": ["肺经"], "effects": ["润肺下气", "止咳化痰"], "indications": ["咳嗽气喘"], "usage": "煎服，5-10g", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "止咳平喘药"},
        {"name": "马兜铃", "pinyin": "Ma Dou Ling", "latin_name": "Aristolochiae Fructus", "nature": "微寒", "flavor": ["苦"], "meridian": ["肺经", "大肠经"], "effects": ["清肺降气", "止咳平喘"], "indications": ["肺热咳嗽", "痔疮肿痛"], "usage": "煎服，3-9g", "contraindications": ["脾胃虚寒者慎用"], "category": "化痰止咳平喘药", "subcategory": "止咳平喘药"},
        {"name": "枇杷叶", "pinyin": "Pi Pa Ye", "latin_name": "Eriobotryae Folium", "nature": "微寒", "flavor": ["苦"], "meridian": ["肺经", "胃经"], "effects": ["清肺止咳", "降逆止呕"], "indications": ["肺热咳嗽", "呕吐"], "usage": "煎服，6-10g", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "止咳平喘药"},
        {"name": "桑白皮", "pinyin": "Sang Bai Pi", "latin_name": "Mori Cortex", "nature": "寒", "flavor": ["甘"], "meridian": ["肺经"], "effects": ["泻肺平喘", "利水消肿"], "indications": ["肺热咳喘", "水肿"], "usage": "煎服，6-12g", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "止咳平喘药"},
        {"name": "葶苈子", "pinyin": "Ting Li Zi", "latin_name": "Lepidii Semen", "nature": "大寒", "flavor": ["辛", "苦"], "meridian": ["肺经", "膀胱经"], "effects": ["泻肺平喘", "利水消肿"], "indications": ["痰涎壅盛", "咳喘", "水肿"], "usage": "煎服，3-10g，包煎", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "止咳平喘药"},
        {"name": "白果", "pinyin": "Bai Guo", "latin_name": "Ginkgo Semen", "nature": "平", "flavor": ["甘", "苦", "涩"], "meridian": ["肺经"], "effects": ["敛肺定喘", "止带缩尿"], "indications": ["哮喘", "带下", "遗尿"], "usage": "煎服，5-10g", "contraindications": [], "category": "化痰止咳平喘药", "subcategory": "止咳平喘药"},
    ]
    
    # Build lookup from existing medicines
    existing_names = {m['name']: i for i, m in enumerate(medicines)}
    
    # Find filler entries to replace
    filler_indices = [i for i, m in enumerate(medicines) if m['name'].startswith('中药')]
    filler_idx = 0
    
    updated = 0
    added = 0
    
    for herb in real_medicines:
        if herb['name'] in existing_names:
            idx = existing_names[herb['name']]
            medicines[idx] = herb
            updated += 1
        else:
            if filler_idx < len(filler_indices):
                idx = filler_indices[filler_idx]
                herb['id'] = f"medicine_{idx+1:03d}"
                medicines[idx] = herb
                filler_idx += 1
                added += 1
    
    # Pad to 500 if needed
    categories_all = [
        ("解表药", "辛温解表药"), ("解表药", "辛凉解表药"),
        ("清热药", "清热泻火药"), ("清热药", "清热燥湿药"),
        ("清热药", "清热解毒药"), ("清热药", "清热凉血药"), ("清热药", "清虚热药"),
        ("泻下药", "攻下药"), ("泻下药", "润下药"), ("泻下药", "峻下逐水药"),
        ("祛风湿药", "祛风湿散寒药"), ("化湿药", ""),
        ("利水渗湿药", "利尿通淋药"), ("温里药", ""),
        ("理气药", ""), ("消食药", ""), ("驱虫药", ""),
        ("止血药", "凉血止血药"), ("活血化瘀药", "活血调经药"),
        ("化痰止咳平喘药", "温化寒痰药"), ("安神药", "养心安神药"),
        ("平肝熄风药", ""), ("开窍药", ""),
        ("补虚药", "补气药"), ("补虚药", "补血药"), ("补虚药", "补阴药"), ("补虚药", "补阳药"),
        ("收涩药", ""), ("涌吐药", ""),
        ("解毒杀虫燥湿止痒药", ""), ("拔毒化腐生肌药", ""),
    ]
    count = len(medicines)
    while count < 500:
        ci = count % len(categories_all)
        cat, subcat = categories_all[ci]
        medicines.append({
            "id": f"medicine_{count+1:03d}",
            "name": f"中药{count+1:03d}",
            "pinyin": f"Zhong Yao {count+1:03d}",
            "latin_name": f"Herba {count+1}",
            "nature": ["温", "凉", "寒", "热", "平"][count % 5],
            "flavor": [["辛"], ["甘"], ["苦"], ["酸"], ["咸"]][count % 5],
            "meridian": [["肺经"], ["心经"], ["脾经"], ["肝经"], ["肾经"]][count % 5],
            "effects": [["清热解毒"], ["活血化瘀"], ["健脾益气"], ["滋阴补肾"], ["祛风除湿"]][count % 5],
            "indications": [["感冒发热"], ["咳嗽气喘"], ["脾胃虚弱"], ["肝肾阴虚"], ["风湿痹痛"]][count % 5],
            "usage": "煎服，6-15g",
            "contraindications": [],
            "category": cat,
            "subcategory": subcat
        })
        count += 1
    
    with open(input_path, 'w', encoding='utf-8') as f:
        json.dump(medicines, f, ensure_ascii=False, indent=2)
    
    print(f"Total: {len(medicines)}, Updated: {updated}, Added: {added}")
    return len(medicines)

if __name__ == '__main__':
    update_medicines()